export const viewData = [
  [
    {
      user_id: 1,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        subscribed_to_newsletter: true,
        uses_dark_mode: false,
      },
    },
    {
      user_id: 2,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        has_marketing_opt_in: true,
        prefers_email_contact: true,
      },
    },
    {
      user_id: 3,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        uses_two_factor_auth: true,
        allows_location_tracking: false,
      },
    },
    {
      user_id: 4,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        subscribed_to_sms_alerts: false,
        has_enabled_autosave: true,
      },
    },
    {
      user_id: 5,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        has_payment_method_on_file: true,
        has_profile_picture: false,
      },
    },
    {
      user_id: 6,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        has_unread_notifications: true,
        uses_google_auth: true,
      },
    },
    {
      user_id: 7,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        is_admin_user: true,
        account_locked: false,
      },
    },
    {
      user_id: 8,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        is_vip_member: false,
        prefers_text_notifications: true,
      },
    },
    {
      user_id: 9,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        uses_biometric_auth: true,
        data_sharing_enabled: false,
      },
    },
    {
      user_id: 10,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        prefers_phone_contact: true,
        has_pending_invitations: false,
      },
    },
    {
      user_id: 11,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        newsletter_opted_out: true,
        is_beta_tester: false,
      },
    },
    {
      user_id: 12,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        has_active_subscription: true,
        app_notifications_enabled: true,
      },
    },
    {
      user_id: 13,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        accepts_push_notifications: true,
        account_verified: false,
      },
    },
    {
      user_id: 14,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        uses_custom_avatar: false,
        app_version_outdated: true,
      },
    },
    {
      user_id: 15,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        access_restricted: false,
        has_loyalty_points: true,
      },
    },
    {
      user_id: 16,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        email_verified: true,
        has_multilingual_support: false,
      },
    },
    {
      user_id: 17,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        linked_social_accounts: true,
        has_used_promo_code: false,
      },
    },
    {
      user_id: 18,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        uses_cloud_storage: true,
        device_rooted: false,
      },
    },
    {
      user_id: 19,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        has_remote_access: true,
        uses_family_sharing: false,
      },
    },
    {
      user_id: 20,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        shares_usage_data: true,
        receives_weekly_summary: true,
      },
    },
    {
      user_id: 21,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        uses_auto_logout: false,
        is_company_employee: true,
      },
    },
    {
      user_id: 22,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        uses_mobile_wallet: true,
        has_account_deactivated: false,
      },
    },
    {
      user_id: 23,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        joined_recently: true,
        uses_voice_commands: false,
      },
    },
    {
      user_id: 24,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        uses_multi_device_sync: true,
        session_active: true,
      },
    },
    {
      user_id: 25,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        subscribed_to_updates: true,
        has_shared_content: false,
      },
    },
    {
      user_id: 26,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        account_suspended: false,
        uses_incognito_mode: true,
      },
    },
    {
      user_id: 27,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        has_enabled_mfa: true,
        uses_advanced_search: false,
      },
    },
    {
      user_id: 28,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        is_content_creator: true,
        has_saved_preferences: false,
      },
    },
    {
      user_id: 29,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        uses_location_history: true,
        requires_admin_approval: false,
      },
    },
    {
      user_id: 30,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        prefers_minimal_notifications: true,
        has_ongoing_project: false,
      },
    },
    {
      user_id: 31,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        is_affiliate_user: true,
        uses_video_background: false,
      },
    },
    {
      user_id: 32,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        participates_in_surveys: false,
        frequent_traveler: true,
      },
    },
    {
      user_id: 33,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        uses_advanced_settings: true,
        is_team_lead: false,
      },
    },
    {
      user_id: 34,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        has_social_media_integration: true,
        allows_public_profile_view: false,
      },
    },
    {
      user_id: 35,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        has_api_access: true,
        subscribed_to_beta_program: false,
      },
    },
    {
      user_id: 36,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        uses_voice_recognition: true,
        app_updates_enabled: false,
      },
    },
    {
      user_id: 37,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        linked_to_bank_account: true,
        uses_secure_backup: false,
      },
    },
    {
      user_id: 38,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        uses_personalized_ads: false,
        prefers_light_mode: true,
      },
    },
    {
      user_id: 39,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        is_power_user: true,
        receives_app_promo: true,
      },
    },
    {
      user_id: 40,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        uses_email_signature: true,
        is_beta_user: false,
      },
    },
    {
      user_id: 41,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        prefers_phone_notifications: true,
        has_mobile_app: false,
      },
    },
    {
      user_id: 42,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        has_family_account: false,
        allows_guest_access: true,
      },
    },
    {
      user_id: 43,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        has_google_integration: false,
        has_multisession: true,
      },
    },
    {
      user_id: 44,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        receives_promotional_offers: true,
        uses_api_key: false,
      },
    },
    {
      user_id: 45,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        prefers_sms_notifications: true,
        has_unverified_email: false,
      },
    },
    {
      user_id: 46,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        uses_mobile_auth: true,
        is_product_tester: false,
      },
    },
    {
      user_id: 47,
      attrs: {
        on_mobile: false,
        located_in_usa: false,
        has_enterprise_business_domain: false,
        has_scheduled_maintenance: false,
        uses_custom_notifications: true,
      },
    },
    {
      user_id: 48,
      attrs: {
        on_mobile: true,
        located_in_usa: true,
        has_enterprise_business_domain: true,
        is_part_of_affiliate_program: false,
        sync_enabled: true,
      },
    },
    {
      user_id: 49,
      attrs: {
        on_mobile: true,
        located_in_usa: false,
        has_enterprise_business_domain: true,
        prefers_desktop_notifications: true,
        has_disabled_ads: false,
      },
    },
    {
      user_id: 50,
      attrs: {
        on_mobile: false,
        located_in_usa: true,
        has_enterprise_business_domain: false,
        uses_social_login: true,
        receives_product_updates: true,
      },
    },
  ],
];

export const attrs = [
  "on_mobile",
  "located_in_usa",
  "has_enterprise_business_domain",
  "subscribed_to_newsletter",
  "uses_dark_mode",
  "has_marketing_opt_in",
  "prefers_email_contact",
  "uses_two_factor_auth",
  "allows_location_tracking",
  "subscribed_to_sms_alerts",
  "has_enabled_autosave",
  "has_payment_method_on_file",
  "has_profile_picture",
  "has_unread_notifications",
  "uses_google_auth",
  "is_admin_user",
  "account_locked",
  "is_vip_member",
  "prefers_text_notifications",
  "uses_biometric_auth",
  "data_sharing_enabled",
  "prefers_phone_contact",
  "has_pending_invitations",
  "newsletter_opted_out",
  "is_beta_tester",
  "has_active_subscription",
  "app_notifications_enabled",
  "accepts_push_notifications",
  "account_verified",
  "uses_custom_avatar",
  "app_version_outdated",
  "access_restricted",
  "has_loyalty_points",
  "email_verified",
  "has_multilingual_support",
  "linked_social_accounts",
  "has_used_promo_code",
  "uses_cloud_storage",
  "device_rooted",
  "has_remote_access",
  "uses_family_sharing",
  "shares_usage_data",
  "receives_weekly_summary",
  "uses_auto_logout",
  "is_company_employee",
  "uses_mobile_wallet",
  "has_account_deactivated",
  "joined_recently",
  "uses_voice_commands",
  "uses_multi_device_sync",
  "session_active",
  "subscribed_to_updates",
  "has_shared_content",
  "account_suspended",
  "uses_incognito_mode",
  "has_enabled_mfa",
  "uses_advanced_search",
  "is_content_creator",
  "has_saved_preferences",
  "uses_location_history",
  "requires_admin_approval",
  "prefers_minimal_notifications",
  "has_ongoing_project",
  "is_affiliate_user",
  "uses_video_background",
  "participates_in_surveys",
  "frequent_traveler",
  "uses_advanced_settings",
  "is_team_lead",
  "has_social_media_integration",
  "allows_public_profile_view",
  "has_api_access",
  "subscribed_to_beta_program",
  "uses_voice_recognition",
  "app_updates_enabled",
  "linked_to_bank_account",
  "uses_secure_backup",
  "uses_personalized_ads",
  "prefers_light_mode",
  "is_power_user",
  "receives_app_promo",
  "uses_email_signature",
  "is_beta_user",
  "prefers_phone_notifications",
  "has_mobile_app",
  "has_family_account",
  "allows_guest_access",
  "has_google_integration",
  "has_multisession",
  "receives_promotional_offers",
  "uses_api_key",
  "prefers_sms_notifications",
  "has_unverified_email",
  "uses_mobile_auth",
  "is_product_tester",
  "has_scheduled_maintenance",
  "uses_custom_notifications",
  "is_part_of_affiliate_program",
  "sync_enabled",
  "prefers_desktop_notifications",
  "has_disabled_ads",
  "uses_social_login",
  "receives_product_updates",
];
